export const countries = {
  Denmark: "🇩🇰",
  "United Kingdom": "🇬🇧",
  "United States": "🇺🇸",
  Canada: "🇨🇦",
  Australia: "🇦🇺",
  "New Zealand": "🇳🇿",
  Ireland: "🇮🇪",
  Switzerland: "🇨🇭",
  Belgium: "🇧🇪",
  Netherlands: "🇳🇱",
  France: "🇫🇷",
  Spain: "🇪🇸",
  Italy: "🇮🇹",
  Sweden: "🇸🇪",
  Finland: "🇫🇮",
  Norway: "🇳🇴",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  China: "🇨🇳",
  Taiwan: "🇹🇼",
  "North Korea": "🇰🇵",
  Kenya: "🇰🇪",
  Uganda: "🇺🇬",
  "South Africa": "🇿🇦",
  Cameroon: "🇨🇲",
  Ghana: "🇬🇭",
  Nigeria: "🇳🇬",
  Zambia: "🇿🇲",
  Zimbabwe: "🇿🇼",
  Sudan: "🇸🇩",
  "Sierra Leone": "🇸🇱",
  Liberia: "🇱🇷",
  Guinea: "🇬🇳",
  "Guinea-Bissau": "🇬🇼",
  "Ivory Coast": "🇨🇮",
  Benin: "🇧🇯",
  Togo: "🇹🇬",
  Mauritania: "🇲🇷",
  "Central African Republic": "🇨🇫",
  "Democratic Republic of the Congo": "🇨🇩",
  "Republic of the Congo": "🇨🇫",
  "Cape Verde": "🇨🇻",
  Russia: "🇷🇺",
  "Czech Republic": "🇨🇿",
  Slovakia: "🇸🇰",
  Slovenia: "🇸🇮",
  Croatia: "🇭🇷",
  "Bosnia and Herzegovina": "🇧🇦",
  Moldova: "🇲🇩",
  Estonia: "🇪🇪",
  Latvia: "🇱🇻",
  Lithuania: "🇱🇹",
  Armenia: "🇦🇲",
  Azerbaijan: "🇦🇿",
  Georgia: "🇬🇪",
  Kazakhstan: "🇰🇿",
  Uzbekistan: "🇺🇿",
  Tajikistan: "🇹🇯",
  Turkmenistan: "🇹🇲",
  Kyrgyzstan: "🇰🇬",
  Mongolia: "🇲🇳",
  Macedonia: "🇲🇰",
  Ukraine: "🇺🇦",
  "United Arab Emirates": "🇦🇪",
  "Saudi Arabia": "🇸🇦",
  Oman: "🇴🇲",
  Qatar: "🇶🇦",
  Kuwait: "🇰🇼",
  Brasil: "🇧🇷",
  Argentina: "🇦🇷",
  Chile: "🇨🇱",
  Colombia: "🇨🇴",
  Ecuador: "🇪🇨",
  Peru: "🇵🇪",
  Venezuela: "🇻🇪",
  Uruguay: "🇺🇾",
  Paraguay: "🇵🇾",
  Bolivia: "🇧🇴",
  Suriname: "🇸🇷",
  "Falkland Islands": "🇫🇰",
  Austria: "🇦🇹",
  Liechtenstein: "🇱🇮",
  "San Marino": "🇸🇲",
  Monaco: "🇲🇨",
  Andorra: "🇦🇩",
  "Vatican City": "🇻🇦",
  Somalia: "🇸🇴",
  Syria: "🇸🇾",
  Portugal: "🇵🇹",
  Bulgaria: "🇧🇬",
  Malta: "🇲🇹",
};
